=== ksnovak/Senior-Year/CIS 444 - Web Programing/Hw7 - XML/hw7.1Novak.dtd
<!--7.1 Create a DTD for a catalog of cars, where each car has the child elements make, model, year, color, engine, number_of_doors, transmission_type, and accessories. The engine element has the child elements number_of_cylinders and fuel_system (carbureted or fuel injected). The accessories element has the attributes radio, air_conditioning, power_windows, power_steering, and power_brakes, each of which is required and has the possible values yes and no. Entities must be declared for the names of popular car models.-->

<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT catalog (car+)>
<!ELEMENT car (make, model, year, color, engine, number_of_doors, transmission_type, accessories)>

<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT engine (number_of_cylinders, fuel_system)>
	<!ELEMENT number_of_cylinders (#PCDATA)>
	<!ELEMENT fuel_system (#PCDATA)>
		<!ATTLIST fuel_system type (carbureted|fuel_injected)>
<!ELEMENT number_of_doors (#PCDATA)>
<!ELEMENT transmission_type (#PCDATA)>
<!ELEMENT accessories (#PCDATA)>
	<!ATTLIST accessories radio CDATA (yes|no) #REQUIRED> 
	<!ATTLIST accessories air_conditioning CDATA (yes|no) #REQUIRED> 
	<!ATTLIST accessories power_windows CDATA (yes|no) #REQUIRED> 
	<!ATTLIST accessories power_steering CDATA (yes|no) #REQUIRED> 
	<!ATTLIST accessories power_brakes CDATA (yes|no) #REQUIRED> 


<!ENTITY m "Mustang">
<!ENTITY w "Wrangler">
<!ENTITY c "Civic">
<!ENTITY a "Accord">

=== ksnovak/Senior-Year/CIS 444 - Web Programing/Hw7 - XML/hw7.6Novak.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!--
7.6 Modify the XSLT style sheet of Exercise 7.5 to format all the car elements in the XML document of Exercise 7.2, and use the style sheet to create a display of the whole document.

NOTE: This document has an xsl stylesheet, hw7.6Novak.xsl.
-->

<!DOCTYPE catalog SYSTEM "hw7.1Novak.dtd">
<?xml-stylesheet type="text/xsl" href="hw7.6Novak.xsl" ?>
	<catalog>
		<car>
			<make>Ford</make>
			<model>Mustang</model>
			<year>1995</year>
			<color>Red</color>
			<engine>
				<number_of_cylinders>8</number_of_cylinders>
				<fuel_system type="carbureted">Carburetion</fuel_system>
			</engine>
			<number_of_doors>2</number_of_doors>
			<transmission_type>manual</transmission_type>
			<accessories radio="yes" air_conditioning="yes" power_windows="yes" power_steering="yes" power_brakes="yes">Fully loaded</accessories>
		</car>
		<car>
			<make>Honda</make>
			<model>Civic</model>
			<year>2003</year>
			<color>Black</color>
			<engine>
				<number_of_cylinders>4</number_of_cylinders>
				<fuel_system type="fuel_injected">Fuel injection</fuel_system>
			</engine>
			<number_of_doors>4</number_of_doors>
			<transmission_type>automatic</transmission_type>
			<accessories radio="yes" air_conditioning="no" power_windows="yes" power_steering="yes" power_brakes="yes"></accessories>
		</car>
		
		<car>
			<make>Jeep</make>
			<model>Wrangler</model>
			<year>2010</year>
			<color>Turquoise</color>
			<engine>
				<number_of_cylinders>6</number_of_cylinders>
				<fuel_system type="carbureted">Carburetion</fuel_system>
			</engine>
			<number_of_doors>4</number_of_doors>
			<transmission_type>manual</transmission_type>
			<accessories radio="yes" air_conditioning="no" power_windows="no" power_steering="yes" power_brakes="yes">Freedom!</accessories>
		</car>
	</catalog>
